on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn clean package
      - uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: v${{github.run_number}}
          files: target/ChitChat-1.3.0.jar
